//
//  DimerProcessor.swift
//
//
//  Created by Philip Turner on 6/11/24.
//

// Resolves two-way collisions.
struct DimerProcessor {
  var atomsToHydrogensMap: [[UInt32]] = []
  var hydrogensToAtomsMap: [[UInt32]] = []
  
  // Extract all sets of connected hydrogen sites from the maps.
  func createHydrogenChains(
    centerTypes: [UInt8]
  ) -> [[UInt32]] {
    var output: [[UInt32]] = []
    for hydrogenID in hydrogensToAtomsMap.indices {
      let atomList = hydrogensToAtomsMap[hydrogenID]
      guard atomList.count == 2 else {
        continue
      }
      
      // First group: (C, H, C)
      let dimerGeometry = DimerGeometry(
        centerTypes: centerTypes,
        atomList: atomList)
      let initialDimerChain = startDimerChain(
        hydrogenID: UInt32(hydrogenID),
        dimerGeometry: dimerGeometry)
      guard let initialDimerChain else {
        continue
      }
      
      // Append several groups of (..., H, C)
      let dimerChain = growDimerChain(
        initialDimerChain: initialDimerChain)
      
      // Even indices: carbon sites
      // Odd indices: hydrogen sites
      var hydrogenChain: [UInt32] = []
      for i in dimerChain.indices where i % 2 == 1 {
        let hydrogenID = dimerChain[i]
        hydrogenChain.append(hydrogenID)
      }
      output.append(hydrogenChain)
    }
    return output
  }
  
  // Returns the bonds generated by the destruction of hydrogens.
  func destroyCollisions(
    hydrogenChains: [[UInt32]]
  ) -> [SIMD2<UInt32>] {
    var collisionStates = [CollisionState](
      repeating: .noCollision,
      count: hydrogensToAtomsMap.count)
    for hydrogenChain in hydrogenChains {
      for i in hydrogenChain.indices {
        // Each dimer chain appears twice. Here, we effectively discard half of
        // the chains. The first one has finalized its dimers. The second
        // chain cannot overwrite them.
        let hydrogenID = Int(hydrogenChain[i])
        guard collisionStates[hydrogenID] == .noCollision else {
          continue
        }
        
        if i % 2 == 0 {
          collisionStates[hydrogenID] = .mergeDimer
        } else {
          collisionStates[hydrogenID] = .keepCollision
        }
      }
    }
    
    return mergeDimers(states: collisionStates)
  }
}

private struct DimerGeometry {
  var bridgeheadID: UInt32?
  var sidewallID: UInt32?
  var bothBridgehead: Bool = true
  var bothSidewall: Bool = true
  
  init(
    centerTypes: [UInt8],
    atomList: [UInt32]
  ) {
    for atomID in atomList {
      switch centerTypes[Int(atomID)] {
      case 2:
        sidewallID = atomID
        bothBridgehead = false
      case 3:
        bridgeheadID = atomID
        bothSidewall = false
      default:
        fatalError("This should never happen.")
      }
    }
  }
}

private enum CollisionState {
  case noCollision
  case keepCollision
  case mergeDimer
}

extension DimerProcessor {
  // The unsorted list must already be guaranteed to have 2 elements.
  private static func opposite(
    original: UInt32,
    unsortedList: [UInt32]
  ) -> UInt32 {
    if original == unsortedList[0] {
      return unsortedList[1]
    } else if original == unsortedList[1] {
      return unsortedList[0]
    } else {
      fatalError("Unexpected hydrogen list.")
    }
  }
  
  private func startDimerChain(
    hydrogenID: UInt32,
    dimerGeometry: DimerGeometry
  ) -> SIMD3<UInt32>? {
    // This list is guaranteed to have 2 elements.
    let atomList = hydrogensToAtomsMap[Int(hydrogenID)]
    
    if dimerGeometry.bothBridgehead {
      let hydrogenList = atomsToHydrogensMap[Int(atomList[0])]
      guard hydrogenList.count == 1 else {
        fatalError("Bridgehead site did not have 1 hydrogen.")
      }
      guard hydrogenID == hydrogenList[0] else {
        fatalError("Unexpected hydrogen list.")
      }
      
      // (C, H, C)
      return SIMD3(
        atomList[0],
        hydrogenID,
        atomList[1])
    } else if dimerGeometry.bothSidewall {
      for atomID in atomList {
        let hydrogenList = atomsToHydrogensMap[Int(atomID)]
        guard hydrogenList.count == 2 else {
          fatalError("Sidewall site did not have 2 hydrogens.")
        }
        
        let oppositeHydrogenID = Self.opposite(
          original: hydrogenID,
          unsortedList: hydrogenList)
        let oppositeAtomList = hydrogensToAtomsMap[Int(oppositeHydrogenID)]
        
        // Cases for 'oppositeAtomList.count':
        // 0: guaranteed to be impossible
        // 1: (oppositeHydrogenID, atomID, hydrogenID) is a terminator
        //    (H, C, H, ...)
        // 2: (something else, oppositeHydrogenID, atomID, hydrogenID)
        //    (..., C, H, C, H, ...)
        // 3: supposedly impossible
        guard oppositeAtomList.count == 1 else {
          guard oppositeAtomList.count == 2 else {
            fatalError("This should never happen.")
          }
          continue
        }
        
        // (oppositeHydrogenID, atomID, hydrogenID, oppositeAtomID)
        // (H, C, H, C, ...)
        let oppositeAtomID = Self.opposite(
          original: atomID,
          unsortedList: atomList)
        return SIMD3(
          atomID,
          hydrogenID,
          oppositeAtomID)
      }
      
      // We found a dimer in the middle of a chain.
      //
      // If there is a long list of dimers, we don't try to travel the entire
      // row length when encountering each bond in the middle. That would be
      // an O(n^2) scaling algorithm. Instead, we only travel when the starting
      // point is one of the two ends.
      //
      // If the chain wraps back onto itself, forming a ring, the entire thing
      // fails to reconstruct.
      return nil
    } else if let bridgeheadID = dimerGeometry.bridgeheadID,
              let sidewallID = dimerGeometry.sidewallID {
      // (C, H, C, ...)
      return SIMD3(
        bridgeheadID,
        hydrogenID,
        sidewallID)
    } else {
      fatalError("This should never happen.")
    }
  }
  
  private func nextDimer(
    hydrogenID: UInt32,
    atomID: UInt32
  ) -> SIMD2<UInt32>? {
    let hydrogenList = atomsToHydrogensMap[Int(atomID)]
    switch hydrogenList.count {
    case 1:
      guard hydrogenID == hydrogenList[0] else {
        fatalError("Unexpected hydrogen list.")
      }
      
      // (..., H, C)
      return nil
    case 2:
      let oppositeHydrogenID = Self.opposite(
        original: hydrogenID,
        unsortedList: hydrogenList)
      let oppositeAtomList = hydrogensToAtomsMap[Int(oppositeHydrogenID)]
      
      // Cases for 'oppositeAtomList.count':
      // 0: guaranteed to be impossible
      // 1: (hydrogenID, atomID, oppositeHydrogenID) is a terminator
      //    (..., H, C, H)
      // 2: (hydrogenID, atomID, oppositeHydrogenID, something else)
      //    (..., H, C, H, C, ...)
      // 3: supposedly impossible
      guard oppositeAtomList.count == 2 else {
        guard oppositeAtomList.count == 1 else {
          fatalError("This should never happen.")
        }
        return nil
      }
      
      // (hydrogenID, atomID, oppositeHydrogenID, expandingAtomID)
      // (..., H, C, H, C, ...)
      let expandingAtomID = Self.opposite(
        original: atomID,
        unsortedList: oppositeAtomList)
      return SIMD2(
        oppositeHydrogenID,
        expandingAtomID)
    default:
      fatalError("This should never happen.")
    }
  }
  
  private func growDimerChain(
    initialDimerChain: SIMD3<UInt32>
  ) -> [UInt32] {
    var dimerChain = [
      initialDimerChain[0],
      initialDimerChain[1],
      initialDimerChain[2],
    ]
    
    // Iteratively search through the topology, seeing whether the chain
    // of linked carbon atoms finally ends.
    //
    // Any unbounded iteration process needs a fail-safe. We cannot guarantee
    // for sure that a bug somewhere down the line hasn't violated the
    // conditions that guarantee convergence. It is extremely problematic to
    // have CPU code freeze, with no way to detect the culprit without
    // compiling everything in debug mode.
    //
    // Rough estimate: 4096 * 0.357 (diamond lattice constant) = 1.46 μm
    // This number far exceeds the current estimate for practical world limit
    // in the renderer (256 nm).
    for _ in 0..<4096 {
      let dimer = nextDimer(
        hydrogenID: dimerChain[dimerChain.count - 2],
        atomID: dimerChain[dimerChain.count - 1])
      if let dimer {
        dimerChain.append(dimer[0])
        dimerChain.append(dimer[1])
      } else {
        return dimerChain
      }
    }
    
    fatalError("Took too many iterations to find length of dimer chain.")
  }
  
  private func mergeDimers(
    states: [CollisionState]
  ) -> [SIMD2<UInt32>] {
    var insertedBonds: [SIMD2<UInt32>] = []
    for hydrogenID in states.indices {
      let state = states[hydrogenID]
      guard state == .mergeDimer else {
        continue
      }
      
      // Fetch the references to the two carbons.
      let atomList = hydrogensToAtomsMap[hydrogenID]
      guard atomList.count == 2 else {
        fatalError("This should never happen.")
      }
      
      // Register a new bond between the two carbons.
      let bond = SIMD2(
        atomList[0],
        atomList[1])
      insertedBonds.append(bond)
    }
    return insertedBonds
  }
}
